Poke Bulbasaur = new Bulbasaur();
Poke Ivysaur = new Ivysaur();
Poke Venusaur = new Venusaur();
Poke Charmander = new Charmander();
Poke Charmeleon = new Charmeleon();
Poke Charizard = new Charizard();
Poke Squirtle = new Squirtle();
Poke Wartortle = new Wartortle();
Poke Blastoise = new Blastoise();
Poke Caterpie = new Caterpie();
Poke Metapod = new Metapod();
Poke Butterfree = new Butterfree();
Poke Weedle = new Weedle();
Poke Kakuna = new Kakuna();
Poke Beedrill = new Beedrill();
Poke Pidgey = new Pidgey();
Poke Pidgeotto = new Pidgeotto();
Poke Pidgeot = new Pidgeot();
Poke Rattata = new Rattata();
Poke Raticate = new Raticate();
Poke Spearow = new Spearow();
Poke Fearow = new Fearow();
Poke Ekans = new Ekans();
Poke Arbok = new Arbok();
Poke Pikachu = new Pikachu();
Poke Raichu = new Raichu();
Poke Sandshrew = new Sandshrew();
Poke Sandslash = new Sandslash();
Poke NidoranF = new NidoranF();
Poke Nidorina = new Nidorina();
Poke Nidoqueen = new Nidoqueen();
Poke NidoranM = new NidoranM();
Poke Nidorino = new Nidorino();
Poke Nidoking = new Nidoking();
Poke Clefairy = new Clefairy();
Poke Clefable = new Clefable();
Poke Vulpix = new Vulpix();
Poke Ninetales = new Ninetales();
Poke Jigglypuff = new Jigglypuff();
Poke Wigglytuff = new Wigglytuff();
Poke Zubat = new Zubat();
Poke Golbat = new Golbat();
Poke Oddish = new Oddish();
Poke Gloom = new Gloom();
Poke Vileplume = new Vileplume();
Poke Paras = new Paras();
Poke Parasect = new Parasect();
Poke Venonat = new Venonat();
Poke Venomoth = new Venomoth();
Poke Diglett = new Diglett();
Poke Dugtrio = new Dugtrio();
Poke Meowth = new Meowth();
Poke Persian = new Persian();
Poke Psyduck = new Psyduck();
Poke Golduck = new Golduck();
Poke Mankey = new Mankey();
Poke Primeape = new Primeape();
Poke Growlithe = new Growlithe();
Poke Arcanine = new Arcanine();
Poke Poliwag = new Poliwag();
Poke Poliwhirl = new Poliwhirl();
Poke Poliwrath = new Poliwrath();
Poke Abra = new Abra();
Poke Kadabra = new Kadabra();
Poke Alakazam = new Alakazam();
Poke Machop = new Machop();
Poke Machoke = new Machoke();
Poke Machamp = new Machamp();
Poke Bellsprout = new Bellsprout();
Poke Weepinbell = new Weepinbell();
Poke Victreebel = new Victreebel();
Poke Tentacool = new Tentacool();
Poke Tentacruel = new Tentacruel();
Poke Geodude = new Geodude();
Poke Graveler = new Graveler();
Poke Golem = new Golem();
Poke Ponyta = new Ponyta();
Poke Rapidash = new Rapidash();
Poke Slowpoke = new Slowpoke();
Poke Slowbro = new Slowbro();
Poke Magnemite = new Magnemite();
Poke Magneton = new Magneton();
Poke Farfetchd = new Farfetchd();
Poke Doduo = new Doduo();
Poke Dodrio = new Dodrio();
Poke Seel = new Seel();
Poke Dewgong = new Dewgong();
Poke Grimer = new Grimer();
Poke Muk = new Muk();
Poke Shellder = new Shellder();
Poke Cloyster = new Cloyster();
Poke Gastly = new Gastly();
Poke Haunter = new Haunter();
Poke Gengar = new Gengar();
Poke Onix = new Onix();
Poke Drowzee = new Drowzee();
Poke Hypno = new Hypno();
Poke Krabby = new Krabby();
Poke Kingler = new Kingler();
Poke Voltorb = new Voltorb();
Poke Electrode = new Electrode();
Poke Exeggcute = new Exeggcute();
Poke Exeggutor = new Exeggutor();
Poke Cubone = new Cubone();
Poke Marowak = new Marowak();
Poke Hitmonlee = new Hitmonlee();
Poke Hitmonchan = new Hitmonchan();
Poke Lickitung = new Lickitung();
Poke Koffing = new Koffing();
Poke Weezing = new Weezing();
Poke Rhyhorn = new Rhyhorn();
Poke Rhydon = new Rhydon();
Poke Chansey = new Chansey();
Poke Tangela = new Tangela();
Poke Kangaskhan = new Kangaskhan();
Poke Horsea = new Horsea();
Poke Seadra = new Seadra();
Poke Goldeen = new Goldeen();
Poke Seaking = new Seaking();
Poke Staryu = new Staryu();
Poke Starmie = new Starmie();
Poke MrMime = new MrMime();
Poke Scyther = new Scyther();
Poke Jynx = new Jynx();
Poke Electabuzz = new Electabuzz();
Poke Magmar = new Magmar();
Poke Pinsir = new Pinsir();
Poke Tauros = new Tauros();
Poke Magikarp = new Magikarp();
Poke Gyarados = new Gyarados();
Poke Lapras = new Lapras();
Poke Ditto = new Ditto();
Poke Eevee = new Eevee();
Poke Vaporeon = new Vaporeon();
Poke Jolteon = new Jolteon();
Poke Flareon = new Flareon();
Poke Porygon = new Porygon();
Poke Omanyte = new Omanyte();
Poke Omastar = new Omastar();
Poke Kabuto = new Kabuto();
Poke Kabutops = new Kabutops();
Poke Aerodactyl = new Aerodactyl();
Poke Snorlax = new Snorlax();
Poke Articuno = new Articuno();
Poke Zapdos = new Zapdos();
Poke Moltres = new Moltres();
Poke Dratini = new Dratini();
Poke Dragonair = new Dragonair();
Poke Dragonite = new Dragonite();
Poke Mewtwo = new Mewtwo();
Poke Mew = new Mew();


ArrayList<Poke>Pokemons = new ArrayList<Poke>();
void setupPokeSet() {
  Pokemons.add(new Venusaur());
  Pokemons.add(new Charizard());
  Pokemons.add(new Blastoise());
  Pokemons.add(new Butterfree());
  Pokemons.add(new Beedrill());
  Pokemons.add(new Pidgeot());
  Pokemons.add(new Raticate());
  Pokemons.add(new Fearow());
  Pokemons.add(new Arbok());
  Pokemons.add(new Raichu());
  Pokemons.add(new Sandslash());
  Pokemons.add(new Nidoqueen());
  Pokemons.add(new Nidoking());
  Pokemons.add(new Clefable());
  Pokemons.add(new Ninetales());
  Pokemons.add(new Wigglytuff());
  Pokemons.add(new Golbat());
  Pokemons.add(new Vileplume());
  Pokemons.add(new Parasect());
  Pokemons.add(new Venomoth());
  Pokemons.add(new Dugtrio());
  Pokemons.add(new Persian());
  Pokemons.add(new Golduck());
  Pokemons.add(new Primeape());
  Pokemons.add(new Arcanine());
  Pokemons.add(new Poliwrath());
  Pokemons.add(new Alakazam());
  Pokemons.add(new Machamp());
  Pokemons.add(new Victreebel());
  Pokemons.add(new Tentacruel());
  Pokemons.add(new Golem());
  Pokemons.add(new Rapidash());
  Pokemons.add(new Slowbro());
  Pokemons.add(new Magneton());
  Pokemons.add(new Farfetchd());
  Pokemons.add(new Dodrio());
  Pokemons.add(new Dewgong());
  Pokemons.add(new Muk());
  Pokemons.add(new Cloyster());
  Pokemons.add(new Gengar());
  Pokemons.add(new Onix());
  Pokemons.add(new Hypno());
  Pokemons.add(new Kingler());
  Pokemons.add(new Electrode());
  Pokemons.add(new Exeggutor());
  Pokemons.add(new Marowak());
  Pokemons.add(new Hitmonlee());
  Pokemons.add(new Hitmonchan());
  Pokemons.add(new Lickitung());
  Pokemons.add(new Weezing());
  Pokemons.add(new Rhydon());
  Pokemons.add(new Chansey());
  Pokemons.add(new Tangela());
  Pokemons.add(new Kangaskhan());
  Pokemons.add(new Seadra());
  Pokemons.add(new Seaking());
  Pokemons.add(new Starmie());
  Pokemons.add(new MrMime());
  Pokemons.add(new Scyther());
  Pokemons.add(new Jynx());
  Pokemons.add(new Electabuzz());
  Pokemons.add(new Magmar());
  Pokemons.add(new Pinsir());
  Pokemons.add(new Tauros());
  Pokemons.add(new Gyarados());
  Pokemons.add(new Lapras());
  //Pokemons.add(new Ditto());
  Pokemons.add(new Vaporeon());
  Pokemons.add(new Jolteon());
  Pokemons.add(new Flareon());
  Pokemons.add(new Porygon());
  Pokemons.add(new Omastar());
  Pokemons.add(new Kabutops());
  Pokemons.add(new Aerodactyl());
  Pokemons.add(new Snorlax());
  Pokemons.add(new Articuno());
  Pokemons.add(new Zapdos());
  Pokemons.add(new Moltres());
  Pokemons.add(new Dragonite());
  Pokemons.add(new Mewtwo());
  Pokemons.add(new Mew());  //index: 79
}

/*
void setupPokeSet() {
  Pokemons.add(new Bulbasaur());
  Pokemons.add(new Ivysaur());
  Pokemons.add(new Venusaur());
  Pokemons.add(new Charmander());
  Pokemons.add(new Charmeleon());
  Pokemons.add(new Charizard());
  Pokemons.add(new Squirtle());
  Pokemons.add(new Wartortle());
  Pokemons.add(new Blastoise());
  Pokemons.add(new Caterpie());
  Pokemons.add(new Metapod());
  Pokemons.add(new Butterfree());
  Pokemons.add(new Weedle());
  Pokemons.add(new Kakuna());
  Pokemons.add(new Beedrill());
  Pokemons.add(new Pidgey());
  Pokemons.add(new Pidgeotto());
  Pokemons.add(new Pidgeot());
  Pokemons.add(new Rattata());
  Pokemons.add(new Raticate());
  Pokemons.add(new Spearow());
  Pokemons.add(new Fearow());
  Pokemons.add(new Ekans());
  Pokemons.add(new Arbok());
  Pokemons.add(new Pikachu());
  Pokemons.add(new Raichu());
  Pokemons.add(new Sandshrew());
  Pokemons.add(new Sandslash());
  Pokemons.add(new NidoranM());
  Pokemons.add(new Nidorina());
  Pokemons.add(new Nidoqueen());
  Pokemons.add(new NidoranF());
  Pokemons.add(new Nidorino());
  Pokemons.add(new Nidoking());
  Pokemons.add(new Clefairy());
  Pokemons.add(new Clefable());
  Pokemons.add(new Vulpix());
  Pokemons.add(new Ninetales());
  Pokemons.add(new Jigglypuff());
  Pokemons.add(new Wigglytuff());
  Pokemons.add(new Zubat());
  Pokemons.add(new Golbat());
  Pokemons.add(new Oddish());
  Pokemons.add(new Gloom());
  Pokemons.add(new Vileplume());
  Pokemons.add(new Paras());
  Pokemons.add(new Parasect());
  Pokemons.add(new Venonat());
  Pokemons.add(new Venomoth());
  Pokemons.add(new Diglett());
  Pokemons.add(new Dugtrio());
  Pokemons.add(new Meowth());
  Pokemons.add(new Persian());
  Pokemons.add(new Psyduck());
  Pokemons.add(new Golduck());
  Pokemons.add(new Mankey());
  Pokemons.add(new Primeape());
  Pokemons.add(new Growlithe());
  Pokemons.add(new Arcanine());
  Pokemons.add(new Poliwag());
  Pokemons.add(new Poliwhirl());
  Pokemons.add(new Poliwrath());
  Pokemons.add(new Abra());
  Pokemons.add(new Kadabra());
  Pokemons.add(new Alakazam());
  Pokemons.add(new Machop());
  Pokemons.add(new Machoke());
  Pokemons.add(new Machamp());
  Pokemons.add(new Bellsprout());
  Pokemons.add(new Weepinbell());
  Pokemons.add(new Victreebel());
  Pokemons.add(new Tentacool());
  Pokemons.add(new Tentacruel());
  Pokemons.add(new Geodude());
  Pokemons.add(new Graveler());
  Pokemons.add(new Golem());
  Pokemons.add(new Ponyta());
  Pokemons.add(new Rapidash());
  Pokemons.add(new Slowpoke());
  Pokemons.add(new Slowbro());
  Pokemons.add(new Magnemite());
  Pokemons.add(new Magneton());
  Pokemons.add(new Farfetchd());
  Pokemons.add(new Doduo());
  Pokemons.add(new Dodrio());
  Pokemons.add(new Seel());
  Pokemons.add(new Dewgong());
  Pokemons.add(new Grimer());
  Pokemons.add(new Muk());
  Pokemons.add(new Shellder());
  Pokemons.add(new Cloyster());
  Pokemons.add(new Gastly());
  Pokemons.add(new Haunter());
  Pokemons.add(new Gengar());
  Pokemons.add(new Onix());
  Pokemons.add(new Drowzee());
  Pokemons.add(new Hypno());
  Pokemons.add(new Krabby());
  Pokemons.add(new Kingler());
  Pokemons.add(new Voltorb());
  Pokemons.add(new Electrode());
  Pokemons.add(new Exeggcute());
  Pokemons.add(new Exeggutor());
  Pokemons.add(new Cubone());
  Pokemons.add(new Marowak());
  Pokemons.add(new Hitmonlee());
  Pokemons.add(new Hitmonchan());
  Pokemons.add(new Lickitung());
  Pokemons.add(new Koffing());
  Pokemons.add(new Weezing());
  Pokemons.add(new Rhyhorn());
  Pokemons.add(new Rhydon());
  Pokemons.add(new Chansey());
  Pokemons.add(new Tangela());
  Pokemons.add(new Kangaskhan());
  Pokemons.add(new Horsea());
  Pokemons.add(new Seadra());
  Pokemons.add(new Goldeen());
  Pokemons.add(new Seaking());
  Pokemons.add(new Staryu());
  Pokemons.add(new Starmie());
  Pokemons.add(new MrMime());
  Pokemons.add(new Scyther());
  Pokemons.add(new Jynx());
  Pokemons.add(new Electabuzz());
  Pokemons.add(new Magmar());
  Pokemons.add(new Pinsir());
  Pokemons.add(new Tauros());
  Pokemons.add(new Magikarp());
  Pokemons.add(new Gyarados());
  Pokemons.add(new Lapras());
  Pokemons.add(new Ditto());
  Pokemons.add(new Eevee());
  Pokemons.add(new Vaporeon());
  Pokemons.add(new Jolteon());
  Pokemons.add(new Flareon());
  Pokemons.add(new Porygon());
  Pokemons.add(new Omanyte());
  Pokemons.add(new Omastar());
  Pokemons.add(new Kabuto());
  Pokemons.add(new Kabutops());
  Pokemons.add(new Aerodactyl());
  Pokemons.add(new Snorlax());
  Pokemons.add(new Articuno());
  Pokemons.add(new Zapdos());
  Pokemons.add(new Moltres());
  Pokemons.add(new Dratini());
  Pokemons.add(new Dragonair());
  Pokemons.add(new Dragonite());
  Pokemons.add(new Mewtwo());
  Pokemons.add(new Mew());
}*/